# required - nginx won't start without this
events {}

# wraps all web server settings
http {
    server {
        # port nginx listens on
        listen 80;

        # where nginx finds your html files inside the container
        root /usr/share/nginx/html;

        # the default file to serve
        index index.html;

        # handle all incoming requests
        location / {
        }
    }
}
